### ISSUE TITLE
problem with python 3.10

### ISSUE THREAD

**Issue by AlexWoroschilow** [venomlab/hexdi#1]
Hi there,

there is a problem with the python 3.10:

`
./lib/python3.10/site-packages/hexdi/__init__.py", line 49, in <module>
    def get_loader(modules: collections.Iterable) -> loader.AbstractBaseLoader:
AttributeError: module 'collections' has no attribute 'Iterable'
`

the fix for the python3.10 is: 

`collections.abc.Iterable`

**Comment by zibertscrem** [comment]
@AlexWoroschilow thank you for submitting the issue, it has been resolved in release https://github.com/venomlab/hexdi/releases/tag/0.2.2
The new patch version 0.2.2 is available on [PyPI](https://pypi.org/project/hexdi/0.2.2/)
